const topics=[
{id:"talk1",number:1,title:"What the Board Said Yes To",summary:"Why KPC is moving from Google Workspace to Microsoft 365 and what the change is intended to accomplish.",memory:"OneDrive is your paddle bag. SharePoint is the C-can.",video:"https://support.microsoft.com/en-us/office/what-is-microsoft-365-c4001f27-e798-4ed8-93e4-656d5d64d509?wt.mc_id=otc_m365basics",body:["The KPC Board approved moving the club from Google Workspace to Microsoft 365 Business Basic. The purpose is not simply to change software. It is to improve how club information is organized, shared, and passed on when volunteers or Board members change roles.","The transition will happen gradually. No one is expected to learn everything at once or become a Microsoft expert. The KitchenTalks will explain each new concept in plain language using examples that make sense for KPC.","The main message is that this is a club knowledge and continuity project designed to make volunteer work easier and reduce confusion."]},
{id:"talk2",number:2,title:"Introducing Microsoft Teams",summary:"How Teams will give committees and working groups one shared place to communicate and work together.",memory:"Email is passing notes across the courts. Teams is everyone meeting at the same court with the same game plan.",video:null,body:["Microsoft Teams will give KPC committees and working groups a shared place to communicate and work together.","Instead of relying on long email chains, duplicate attachments, side conversations, and files stored in different places, each team can have its own area for discussions, documents, notes, decisions, and follow-up items.","Email will still be used for formal communication and messages outside the club. Teams will be used mainly for internal collaboration when several people are working on the same topic or project.","The goal is fewer lost emails, fewer duplicate attachments, clearer conversations, easier access to current information, and smoother handoffs when volunteer roles change."]},
{id:"talk3",number:3,title:"Personal Sign-Ins and Role-Based Access",summary:"Why each volunteer will sign in with an individual KPC account and receive access based on their role.",memory:"Every player wears their own name tag but gets access to the courts and equipment needed for their role.",video:null,body:["KPC currently has some accounts that are tied to a role rather than to an individual person. These accounts often require several volunteers to share the same password.","Shared passwords can create confusion. It may become unclear who has the password, whether it has been changed, whose phone is connected to the account, or who still has access after changing roles.","Under Microsoft 365, each person will sign in using their own KPC account. KPC will then give that person access to the files, mailboxes, teams, and information needed for their work.","When someone changes roles, their access can be updated without changing shared passwords or trying to determine who still has the login information.","This approach provides clearer responsibility, easier handoffs, and better protection for club information."]},
{id:"talk4",number:4,title:"How KPC Email Accounts Will Work",summary:"How personal sign-ins, permanent role addresses and shared function mailboxes will work after migration.",memory:"Sign in as yourself, then open the KPC mailboxes you are authorized to use.",video:null,body:["As part of the Microsoft 365 migration, KPC email addresses will be reorganized so that people sign in using their own KPC accounts.","Permanent role addresses such as president@, vice.president@, secretary@, and treasurer@ will remain. The person holding that role will access the role mailbox through their own account.","Shared function addresses such as membership@, communications@, scheduling@, tournaments@, and itconsult@ will also remain. Access will be given to the appropriate volunteers through their individual accounts.","Numbered director accounts such as director1@ and director8@ will be replaced with accounts assigned to individual directors. KPC will not use a shared directors@ mailbox.","This direction will be reviewed with several Board members before the final account structure is approved and implemented.","Volunteers are also being asked to complete a survey so IT can identify information that may not be visible from the administrative side, including email signatures, templates, contacts, calendars, forwarding rules, filters, local Outlook folders, and connected applications.","Google has advised KPC that, beginning October 20, 2026, people who access the Google Cloud console using a KPC-managed account will be required to use 2-Step Verification. This notice applies specifically to Google Cloud console access and does not mean that everyone using Gmail, Drive, Sheets, or Slides must make an immediate change.","Volunteers using shared KPC accounts should not enable 2-Step Verification themselves. Connecting a shared account to one person’s phone or authenticator could prevent other authorized volunteers from signing in.","KPC IT will address shared accounts and stronger authentication as part of the Microsoft 365 migration."]}
];

const quizzes={
erne:{name:"Erne’s Warm-Up",host:"Erne",questions:[
{q:"Which Microsoft tool will KPC use for email and calendars?",a:["Outlook","Teams","SharePoint","OneDrive"],correct:0,why:"Outlook is the KPC email and calendar tool."},
{q:"Where will committees mainly communicate and work together?",a:["Teams","OneDrive","A personal email account","A USB drive"],correct:0,why:"Teams will be the main workspace for committee conversations, meetings and shared work."},
{q:"Do you need to learn every Microsoft 365 feature before launch?",a:["Yes, all of them","No, only what you need for your role","Only Excel","Only if you are on the board"],correct:1,why:"KitchenTalks are designed so you can learn practical tasks when you need them."},
{q:"What is OneDrive mainly for?",a:["Your own drafts and working files","All official KPC records","Public website pages","Committee announcements"],correct:0,why:"OneDrive is your individual KPC work area. Shared committee records belong in Teams or SharePoint."},
{q:"Should two volunteers share one KPC account?",a:["Yes","Only on weekends","No","Only for meetings"],correct:2,why:"Each volunteer should use an individual account for security and accountability."},
{q:"What should you do with an unexpected sign-in approval request?",a:["Approve it quickly","Ignore or deny it and report it","Send it to another volunteer","Post it in Teams"],correct:1,why:"Never approve a sign-in you did not start."},
{q:"Which statement best describes SharePoint?",a:["KPC’s organized shared information and file system","A video meeting camera","A password manager","A spreadsheet"],correct:0,why:"SharePoint organizes shared KPC information and also stores files accessed through Teams."},
{q:"What is the main idea behind KitchenTalks?",a:["Learn everything in one day","Learn on demand in short practical lessons","Take a formal certification exam","Replace all KPC meetings"],correct:1,why:"KitchenTalks provide short help when a task or question comes up."}
]},
smash:{name:"Smash Challenge",host:"Smash",questions:[
{q:"Three committee members need to edit the same spreadsheet. What is the best approach?",a:["Email three separate copies","Work from one shared file in Teams","Save it only on one person’s computer","Print it and make handwritten changes"],correct:1,why:"One shared file reduces duplicate versions and keeps the current work in one place."},
{q:"A draft procedure is not ready for the committee. Where should you work on it first?",a:["Your KPC OneDrive","The public website","A personal social media account","The official minutes folder"],correct:0,why:"OneDrive is appropriate for an individual early draft. Move it to the shared workspace when it becomes committee work."},
{q:"Why should an official committee document not remain only in one volunteer’s OneDrive?",a:["The font may change","Others may lose access when the role changes","It cannot contain numbers","OneDrive does not save files"],correct:1,why:"Shared KPC records need continuity beyond any one volunteer or role."},
{q:"You need to send someone the latest shared document. What is usually best?",a:["Send a link to the shared file","Attach a new copy every time","Take a picture of the screen","Copy it into a personal account"],correct:0,why:"A link points people to the current shared version instead of creating more copies."},
{q:"You receive a Teams meeting invitation in Outlook. Where can you join?",a:["From the invitation or Teams calendar","Only from SharePoint","Only from OneDrive","Only from Word"],correct:0,why:"Outlook and Teams work together, so the meeting can be joined from the invitation or Teams calendar."},
{q:"A volunteer asks for your password so they can finish a task. What should you do?",a:["Share it for one hour","Decline and help them get proper access","Write it on paper","Change it to an easier password"],correct:1,why:"Passwords and accounts are individual. Access should be granted to the person, not borrowed through another account."},
{q:"Where should approved policies and lasting KPC records normally live?",a:["An approved shared SharePoint or Teams location","Only in personal email","Only on a home computer","In an unsent draft"],correct:0,why:"Official information belongs in an approved shared location that remains available as volunteers change."},
{q:"A Microsoft video looks slightly different from the KPC screen. What should you do?",a:["Assume the entire lesson is wrong","Use the KPC explanation and screenshots as the primary guide","Delete your account","Stop using Microsoft 365"],correct:1,why:"Microsoft interfaces change. KPC-specific guidance will show how the club has configured the tools."}
]}};

const topicGrid=document.querySelector("#topicGrid");
const topicDialog=document.querySelector("#topicDialog");
const topicContent=document.querySelector("#topicContent");
const quizDialog=document.querySelector("#quizDialog");
const quizContent=document.querySelector("#quizContent");

function renderTopics(){topicGrid.innerHTML=topics.map(t=>`<button class="topic-card" data-topic="${t.id}" aria-label="Open ${t.title}"><h3>${t.title}</h3><p>${t.summary}</p></button>`).join("")}
function openTopic(id){const t=topics.find(x=>x.id===id);if(!t)return;topicContent.innerHTML=`<p class="eyebrow">M365 KitchenTalk #${t.number}</p><h2>${t.title}</h2><div class="full-talk">${t.body.map(p=>`<p>${p}</p>`).join("")}</div><div class="memory-hook"><strong>Less Computer, More Pickleball</strong><p>${t.memory}</p></div><div class="actions">${t.video?`<a class="button dark" href="${t.video}" target="_blank" rel="noopener noreferrer">Watch a short video</a>`:`<button class="button outline" disabled title="Video will be added after it is reviewed">Video coming soon</button>`}</div>`;topicDialog.showModal()}

document.querySelector("[data-close-topic]").addEventListener("click",()=>topicDialog.close());
topicDialog.addEventListener("click",e=>{if(e.target===topicDialog)topicDialog.close()});

let quizState=null;
function startQuiz(type){quizState={type,index:0,score:0,answered:false};renderQuestion();quizDialog.showModal()}
function renderQuestion(){const quiz=quizzes[quizState.type];const item=quiz.questions[quizState.index];const pct=(quizState.index/quiz.questions.length)*100;quizContent.innerHTML=`<div class="quiz-top"><span>${quiz.host} asks</span><span>Question ${quizState.index+1} of ${quiz.questions.length}</span></div><div class="progress"><span style="width:${pct}%"></span></div><p class="eyebrow">${quiz.name}</p><p class="question">${item.q}</p><div class="answers">${item.a.map((answer,i)=>`<button class="answer" data-answer="${i}">${answer}</button>`).join("")}</div><div id="feedback"></div>`}
function chooseAnswer(index){if(quizState.answered)return;quizState.answered=true;const quiz=quizzes[quizState.type];const item=quiz.questions[quizState.index];const buttons=[...quizContent.querySelectorAll(".answer")];buttons.forEach((b,i)=>{b.disabled=true;if(i===item.correct)b.classList.add("correct");if(i===index&&i!==item.correct)b.classList.add("incorrect")});const good=index===item.correct;if(good)quizState.score++;document.querySelector("#feedback").innerHTML=`<div class="feedback"><strong>${good?"Nice rally!":"Good try."}</strong><p>${item.why}</p></div><div class="next-row"><button class="button dark" data-next>${quizState.index+1===quiz.questions.length?"See my result":"Next question"}</button></div>`}
function nextQuestion(){const quiz=quizzes[quizState.type];quizState.index++;quizState.answered=false;if(quizState.index>=quiz.questions.length){renderResult();return}renderQuestion()}
function renderResult(){const quiz=quizzes[quizState.type];const ratio=quizState.score/quiz.questions.length;let message=ratio>=.875?"You are ready to help lead the rally.":ratio>=.625?"You have a strong start. A few KitchenTalks will fill the gaps.":"This is exactly what KitchenTalks are for. Start with the readiness topics and play again later.";quizContent.innerHTML=`<p class="eyebrow">${quiz.name} complete</p><h2>${quizState.type==="erne"?"Warm-up finished":"Challenge finished"}</h2><div class="score">${quizState.score}/${quiz.questions.length}</div><p>${message}</p><p>Your result stays on this device only and disappears when you close the game.</p><div class="actions"><button class="button dark" data-replay>Play again</button><button class="button outline" data-close-result>Back to KitchenTalks</button></div>`}

document.addEventListener("click",e=>{const topic=e.target.closest("[data-topic]");if(topic)openTopic(topic.dataset.topic);const start=e.target.closest("[data-start-quiz]");if(start)startQuiz(start.dataset.startQuiz);const answer=e.target.closest("[data-answer]");if(answer)chooseAnswer(Number(answer.dataset.answer));if(e.target.closest("[data-next]"))nextQuestion();if(e.target.closest("[data-replay]"))startQuiz(quizState.type);if(e.target.closest("[data-close-result]"))quizDialog.close()});
document.querySelector("[data-close-quiz]").addEventListener("click",()=>quizDialog.close());
quizDialog.addEventListener("click",e=>{if(e.target===quizDialog)quizDialog.close()});
renderTopics();