const kitchenTalkIcons={
  talk1:`<svg viewBox="0 0 64 64" aria-hidden="true"><rect x="15" y="10" width="34" height="44" rx="6" fill="none" stroke="currentColor" stroke-width="4"/><path d="M24 10v-2h16v2" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round"/><path d="m23 34 6 6 13-15" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/><circle cx="49" cy="49" r="8" fill="var(--yellow)" stroke="currentColor" stroke-width="3"/><circle cx="46" cy="46" r="1.5" fill="currentColor"/><circle cx="52" cy="52" r="1.5" fill="currentColor"/></svg>`,
  talk2:`<svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="22" cy="24" r="8" fill="none" stroke="currentColor" stroke-width="4"/><circle cx="43" cy="22" r="7" fill="none" stroke="currentColor" stroke-width="4"/><path d="M9 50c1-11 7-16 14-16s13 5 14 16" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round"/><path d="M36 36c3-4 7-6 11-6 7 0 11 5 12 14" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round"/><path d="M10 10h28v12H21l-7 6v-6h-4z" fill="var(--yellow)" stroke="currentColor" stroke-width="3" stroke-linejoin="round"/></svg>`,
  talk3:`<svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="25" cy="20" r="9" fill="none" stroke="currentColor" stroke-width="4"/><path d="M10 52c1-13 7-20 15-20s14 7 15 20" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round"/><rect x="37" y="29" width="19" height="22" rx="4" fill="var(--yellow)" stroke="currentColor" stroke-width="3"/><circle cx="46.5" cy="38" r="3" fill="none" stroke="currentColor" stroke-width="3"/><path d="M46.5 41v5" stroke="currentColor" stroke-width="3" stroke-linecap="round"/></svg>`,
  talk4:`<svg viewBox="0 0 64 64" aria-hidden="true"><rect x="8" y="15" width="48" height="34" rx="6" fill="none" stroke="currentColor" stroke-width="4"/><path d="m11 20 21 17 21-17" fill="none" stroke="currentColor" stroke-width="4" stroke-linejoin="round"/><circle cx="49" cy="46" r="10" fill="var(--yellow)" stroke="currentColor" stroke-width="3"/><circle cx="49" cy="43" r="3" fill="none" stroke="currentColor" stroke-width="2.5"/><path d="M44 51c1-4 3-6 5-6s4 2 5 6" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/></svg>`
};

function renderKitchenTalkIcons(){
  topicGrid.innerHTML=topics.map(t=>`<button class="topic-card" data-topic="${t.id}" aria-label="Open ${t.title}"><span class="topic-icon">${kitchenTalkIcons[t.id]||""}</span><span class="topic-copy"><h3>${t.title}</h3><p>${t.summary}</p></span></button>`).join("");
}

renderKitchenTalkIcons();