window.KPCLearning=(()=>{
const helpContact={label:"KPC Technology Team",instructions:"Email ITConsult@kamloopspickleballclub.ca with what you were trying to do, the device you were using and the message you saw.",peerHelp:"Ask another board or committee member first. They may have already solved the same problem.",safety:"Never send your password, temporary password, multifactor authentication code or sign-in approval number."};
const learningPaths=[
{id:"start-here",title:"Your First KPC Sign-In",description:"Get into your KPC account, create your private password and complete the security setup.",outcome:"I can sign in safely and find the Microsoft 365 tools KPC uses.",label:"Begin here if you are new",featured:true,restricted:false,mascot:"assets/mascots/start-here.svg",mascotAlt:"Simple sign-in icon.",lessons:["m365-overview","first-time-m365-sign-in"]},
{id:"email-meetings",title:"Outlook: Email and Calendar",description:"Use KPC email and calendars in Outlook—and bring other email accounts into the same Outlook app when appropriate.",outcome:"I can use Outlook without constantly signing in to different places.",featured:true,restricted:false,mascot:"assets/mascots/email-meetings.svg",mascotAlt:"Simple Outlook icon.",lessons:["outlook-overview","open-outlook","outlook-other-accounts","shared-mailboxes","outlook-calendar","create-teams-meeting","join-teams-meeting"]},
{id:"committee-work",title:"Teams: Working Together",description:"Use Teams as the shared working space for the board, committees and projects you are authorized to access.",outcome:"I can find my Teams, follow conversations and work in shared files.",featured:true,restricted:false,mascot:"assets/mascots/committee-work.svg",mascotAlt:"Simple Teams icon.",lessons:["teams-at-kpc","open-committee-team","channels-conversations","find-committee-files","edit-shared-document","send-a-link"]},
{id:"files-what-goes-where",title:"Shared Information: OneDrive and SharePoint",description:"Understand the difference between your own working files, shared team files and KPC's organized information centre or intranet.",outcome:"I can find information and choose an appropriate place for my work without memorizing a folder map.",featured:false,restricted:false,mascot:"assets/mascots/files.svg",mascotAlt:"Simple shared information icon.",memoryAid:"OneDrive is your working bag. Teams is the shared court. SharePoint is the organized clubhouse and information centre behind it.",lessons:["onedrive-personal-files","teams-shared-work","sharepoint-intranet","find-shared-information","find-current-version","links-vs-attachments"]},
{id:"staying-safe",title:"Protecting Your KPC Account",description:"Recognize suspicious requests, protect club information and know when to ask for help.",outcome:"I can use my KPC account safely and respond appropriately when something seems wrong.",featured:false,restricted:false,mascot:"assets/mascots/staying-safe.svg",mascotAlt:"Simple security icon.",lessons:["individual-accounts","what-mfa-does","suspicious-sign-ins","basic-phishing","safe-sharing","report-problem"]},
{id:"kpc-administration",title:"Microsoft 365 Administration",description:"Account, access and continuity tasks for specifically authorized KPC administrators.",outcome:"I can complete routine administration safely and preserve continuity.",label:"Authorized administrators only",featured:false,restricted:true,mascot:"assets/mascots/administration.svg",mascotAlt:"Simple administration icon.",lessons:["add-user","offboard-user","manage-licence","reset-password","committee-access","mailbox-permissions","admin-continuity"]}
];
const titles={
"start-here":[["m365-overview","The KPC tools you will use"],["first-time-m365-sign-in","Sign in for the first time"]],
"email-meetings":[["outlook-overview","How Outlook brings email and calendars together"],["open-outlook","Open your KPC Outlook"],["outlook-other-accounts","Add another email account to Outlook"],["shared-mailboxes","Open a KPC role or shared mailbox"],["outlook-calendar","Use your Outlook calendar"],["create-teams-meeting","Create a Teams meeting from Outlook"],["join-teams-meeting","Join a Teams meeting"]],
"committee-work":[["teams-at-kpc","How KPC uses Teams"],["open-committee-team","Open the Teams you have access to"],["channels-conversations","Follow conversations and channels"],["find-committee-files","Find shared team files"],["edit-shared-document","Work together in one shared document"],["send-a-link","Send a link instead of another copy"]],
"files-what-goes-where":[["onedrive-personal-files","Use OneDrive for your own KPC working files"],["teams-shared-work","Use Teams for work shared with others"],["sharepoint-intranet","Understand SharePoint and the KPC intranet"],["find-shared-information","Find the information available to your role"],["find-current-version","Recognize the current shared version"],["links-vs-attachments","Choose a link or an attachment"]],
"staying-safe":[["individual-accounts","Use your own KPC account"],["what-mfa-does","Understand sign-in verification"],["suspicious-sign-ins","Handle an unexpected sign-in request"],["basic-phishing","Spot a suspicious message"],["safe-sharing","Share KPC information safely"],["report-problem","Know when and how to ask for help"]],
"kpc-administration":[["add-user","Add a volunteer account"],["offboard-user","Update access when someone leaves or changes roles"],["manage-licence","Manage a licence"],["reset-password","Help with account recovery"],["committee-access","Manage role and Team access"],["mailbox-permissions","Manage shared mailbox access"],["admin-continuity","Keep administration from depending on one person"]]
};
const details={
"m365-overview":{description:"Meet the small set of Microsoft 365 tools KPC volunteers use and understand how they work together.",outcome:"I can recognize Outlook, Teams, OneDrive and SharePoint and know the basic purpose of each.",whyItMatters:"You only need to understand the tools connected to your role—not every Microsoft 365 feature.",steps:["Outlook is where you use email and calendars.","Teams is where boards, committees and project groups work together.","OneDrive is your personal KPC working area.","SharePoint organizes shared information and can provide KPC's internal information centre or intranet."],practiceTask:"Say which tool you would open for email, teamwork and your own draft document."},
"first-time-m365-sign-in":{description:"Follow the complete first-time KPC sign-in process, including your new password, sign-in verification and finding your apps.",outcome:"I can enter my KPC account safely and finish the required security steps.",whyItMatters:"This one guided process prepares you to use every KPC Microsoft 365 tool connected to your role.",estimatedMinutes:6,kpcVideo:{url:"assets/videos/first-time-signing-into-m365-web.mp4",status:"available",title:"Signing into Microsoft 365 for the first time"},steps:["Go to login.microsoftonline.com.","Enter the KPC email address provided to you.","Use the temporary password from KPC and create a private password when prompted.","Complete the on-screen sign-in verification setup.","Approve only sign-in requests that you started.","Open the app launcher and locate Outlook, Teams and OneDrive."],practiceTask:"After the video, identify where you would open Outlook and Teams.",status:"video available",contentStatus:["KPC demonstration available","written guide available"]},
"outlook-overview":{description:"See how Outlook can bring your KPC email, calendar and—when appropriate—other email accounts into one app.",outcome:"I can explain why Outlook may reduce the number of separate places I need to check.",whyItMatters:"A single Outlook app can make volunteer work easier while keeping each mailbox and calendar distinct.",steps:["Use your KPC account to open Outlook.","Your KPC mailbox and calendar appear together.","Outlook can also connect other supported email accounts you already use.","Adding another account does not merge the organizations or give KPC access to your personal mailbox."],practiceTask:"Think about whether viewing your KPC and another mailbox in one Outlook app would make your routine easier."},
"outlook-other-accounts":{description:"Add another supported email account to the Outlook app so you can switch between mailboxes without repeated browser sign-ins.",outcome:"I can add or switch between accounts in Outlook while keeping them separate.",whyItMatters:"This can reduce sign-in frustration without combining your personal and KPC information.",steps:["Open the Outlook app settings.","Choose the option to add an account.","Enter the email address for the additional account.","Follow that account provider's sign-in steps.","Use the account switcher to move between separate inboxes and calendars."],practiceTask:"Locate the account switcher in Outlook without adding an account yet."},
"shared-mailboxes":{description:"Open a KPC role or shared mailbox that has been assigned to your individual account.",outcome:"I can use an authorized KPC mailbox without sharing another person's password.",whyItMatters:"Access follows the role while each volunteer continues to sign in as themselves.",steps:["Sign in to Outlook with your own KPC account.","Open the account or folder menu.","Look for the shared mailbox assigned to you, or choose Open another mailbox when instructed.","Confirm which address will send the message before sending."],practiceTask:"Identify the difference between your own KPC mailbox and a role or function mailbox."},
"sharepoint-intranet":{description:"Understand SharePoint as KPC's organized shared information platform and potential internal information centre.",outcome:"I can recognize that SharePoint supports both shared files and an intranet-style place for lasting KPC information.",whyItMatters:"SharePoint helps information remain available as board and committee volunteers change.",steps:["SharePoint stores and organizes shared KPC information.","Files used through Teams are stored in SharePoint behind the scenes.","A SharePoint communication site can act as KPC's internal information centre or intranet.","What you can see depends on the access connected to your role."],practiceTask:"Describe the difference between a Team's working area and an intranet page used to publish lasting information."},
"find-shared-information":{description:"Use Teams, SharePoint navigation and search to find information made available to your role.",outcome:"I can find shared information without relying on a permanent folder-by-folder map.",whyItMatters:"Committee names, structures and storage locations may evolve, but navigation and search remain useful.",steps:["Start in the Team or KPC information area connected to your role.","Use clear page, channel and library names as signposts.","Use search when you do not know the exact location.","Ask another board or committee member when context is missing."],practiceTask:"Search for a broad document type, such as minutes, policies or templates, rather than memorizing a specific folder path."},
"teams-at-kpc":{description:"Understand Teams as the shared working space for boards, committees and projects.",outcome:"I can explain what the Teams I have access to are for.",whyItMatters:"Teams keeps conversations, meetings and shared files together for the people doing the work.",steps:["Open Teams with your KPC account.","You will see only the Teams and areas assigned to your role.","Use conversations for work that others in the group need to follow.","Use the Files area for documents the group works on together."],practiceTask:"Name one type of work that belongs in a shared Team rather than only in personal email."},
"create-teams-meeting":{description:"Create and send a Teams meeting invitation from Outlook.",outcome:"I can create a Teams meeting and invite the right people.",whyItMatters:"Outlook and Teams work together so the date, invitation and joining link stay in one place.",estimatedMinutes:2,kpcVideo:{url:"assets/videos/creating-a-teams-meeting-web.mp4",status:"available",title:"Create a Teams Meeting"},steps:["Open the Outlook calendar.","Choose New event.","Add the title, date, time and attendees.","Turn on the Teams meeting option.","Review and send the invitation."],practiceTask:"Create a practice meeting without sending it and confirm that a Teams link appears.",status:"video available",contentStatus:["KPC demonstration available","written guide available"]}
};
const lessons=[];
Object.entries(titles).forEach(([pathId,items])=>items.forEach(([id,title])=>{const d=details[id]||{};lessons.push({id,pathId,title,description:d.description||"A short practical lesson for this part of KPC Microsoft 365.",outcome:d.outcome||`I can ${title.charAt(0).toLowerCase()}${title.slice(1)}.`,whyItMatters:d.whyItMatters||"This supports clear, shared and sustainable volunteer work.",estimatedMinutes:d.estimatedMinutes||4,microsoftVideo:null,kpcVideo:d.kpcVideo||{url:"",status:"coming-soon"},screenshots:[],steps:d.steps||[],practiceTask:d.practiceTask||"",knowledgeCheck:[],troubleshooting:[],relatedKitchenTalkId:null,status:d.status||(d.steps?"written guide available":"lesson outline"),contentStatus:d.contentStatus||(d.steps?["written guide available"]:["lesson being developed"])})}));
return{learningPaths,lessons,helpContact};
})();