const helpContact={label:"Ask KPC for help",instructions:"Include what you were trying to do, the device you were using, and the exact message you saw. Do not send your password."};

const learningPaths=[
{id:"start-here",title:"Start Here",description:"Sign in, find your Microsoft 365 apps and protect your KPC account.",outcome:"I can safely access my KPC account and find the tools I need.",audience:"everyone",label:"Recommended for everyone",featured:true,restricted:false,mascot:"assets/mascots/start-here.png",mascotAlt:"KPC pickleball character welcoming a volunteer to the Start Here path.",lessons:["m365-overview","kpc-use-m365","sign-in-kpc","find-apps","set-up-mfa","unexpected-sign-in","get-help"]},
{id:"email-meetings",title:"Email and Meetings",description:"Use KPC email, manage invitations and join online meetings.",outcome:"I can use KPC email, manage invitations and participate in meetings.",featured:false,restricted:false,mascot:"assets/mascots/email-meetings.png",mascotAlt:"KPC pickleball character holding an envelope and calendar.",lessons:["open-outlook","send-reply-email","personal-email","role-addresses","shared-mailboxes","outlook-calendar","accept-invitation","join-teams-meeting","share-screen"]},
{id:"committee-work",title:"Working With Your Committee",description:"Find conversations, files and shared work for your KPC committee.",outcome:"I can work with my committee and find the information we share.",featured:true,restricted:false,mascot:"assets/mascots/committee-work.png",mascotAlt:"KPC pickleball characters collaborating around a shared document.",lessons:["teams-at-kpc","open-committee-team","channels-conversations","find-committee-files","edit-shared-document","avoid-duplicates","send-a-link","committee-knowledge-check"]},
{id:"files-what-goes-where",title:"Files — What Goes Where?",description:"Understand OneDrive, Teams and SharePoint without the technical language.",outcome:"I can decide where a KPC document belongs and find it again later.",featured:false,restricted:false,mascot:"assets/mascots/files.png",mascotAlt:"KPC pickleball character organizing a paddle bag and shared equipment.",memoryAid:"OneDrive is your paddle bag. SharePoint is the KPC equipment room.",lessons:["onedrive-personal-files","teams-shared-work","sharepoint-lasting-info","move-draft","find-current-version","share-file-safely","official-records","links-vs-attachments"]},
{id:"staying-safe",title:"Staying Safe",description:"Protect your KPC account, club information and other volunteers.",outcome:"I can recognize common risks and protect KPC information.",featured:false,restricted:false,mascot:"assets/mascots/staying-safe.png",mascotAlt:"KPC pickleball character protecting a paddle bag with a shield.",lessons:["individual-accounts","no-shared-passwords","what-mfa-does","suspicious-sign-ins","basic-phishing","safe-sharing","protect-information","report-problem"]},
{id:"kpc-administration",title:"KPC Administration",description:"Routine Microsoft 365 tasks for authorized KPC administrators.",outcome:"I can complete routine KPC Microsoft 365 administration safely.",audience:"administrators",label:"For authorized administrators only",featured:false,restricted:true,mascot:"assets/mascots/administration.png",mascotAlt:"KPC pickleball character holding a clipboard and access list.",lessons:["add-user","offboard-user","manage-licence","reset-password","committee-access","mailbox-permissions","add-administrator","review-access-changes","admin-continuity"]}
];

const officialVideos={
"m365-overview":{publisher:"Microsoft",title:"What is Microsoft 365?",url:"https://support.microsoft.com/en-us/office/what-is-microsoft-365-c4001f27-e798-4ed8-93e4-656d5d64d509?wt.mc_id=otc_m365basics",duration:"Short overview",captions:"Check on source",transcriptUrl:"https://support.microsoft.com/en-us/office/what-is-microsoft-365-c4001f27-e798-4ed8-93e4-656d5d64d509?wt.mc_id=otc_m365basics",lastReviewed:"2026-07-26"},
"join-teams-meeting":{publisher:"Microsoft",title:"Get started with meetings",url:"https://support.microsoft.com/en-us/office/get-started-with-meetings-909b75b4-5448-455c-9c9a-5115acf4d3d8",duration:"Short lesson",captions:"Check on source",transcriptUrl:"https://support.microsoft.com/en-us/office/get-started-with-meetings-909b75b4-5448-455c-9c9a-5115acf4d3d8",lastReviewed:"2026-07-26"},
"onedrive-personal-files":{publisher:"Microsoft",title:"OneDrive basics",url:"https://support.microsoft.com/en-us/office/video-onedrive-basics-fe8aab1e-3d1a-4a65-a9b6-77b79b6dbb30",duration:"Short lesson",captions:"Check on source",transcriptUrl:"https://support.microsoft.com/en-us/office/video-onedrive-basics-fe8aab1e-3d1a-4a65-a9b6-77b79b6dbb30",lastReviewed:"2026-07-26"},
"teams-at-kpc":{publisher:"Microsoft",title:"Microsoft Teams help and learning",url:"https://support.microsoft.com/en-us/teams",duration:"Reference",captions:"Varies",transcriptUrl:"https://support.microsoft.com/en-us/teams",lastReviewed:"2026-07-26"},
"set-up-mfa":{publisher:"Microsoft",title:"Use Microsoft Authenticator",url:"https://support.microsoft.com/en-us/account-billing/how-to-use-the-microsoft-authenticator-app-9783c865-0308-42fb-a519-8cf666fe0acc",duration:"Short lesson",captions:"Check on source",transcriptUrl:"https://support.microsoft.com/en-us/account-billing/how-to-use-the-microsoft-authenticator-app-9783c865-0308-42fb-a519-8cf666fe0acc",lastReviewed:"2026-07-26"}
};

const detailedCommitteeLessons={
"teams-at-kpc":{title:"What Teams will do for KPC",description:"Understand why committee conversations, meetings and shared work will be kept together.",outcome:"I can explain what my committee Team is for.",whyItMatters:"Your committee Team gives volunteers one shared place to find the work instead of searching through separate email chains and attachments.",estimatedMinutes:4,steps:["Think of Teams as your committee's shared working area.","Use conversations for updates that belong with committee work.","Use the Files area for documents the committee works on together.","Use Outlook for formal email and messages outside the committee."],practiceTask:"Name one current committee task that would be easier to find if its conversation and file were kept together.",knowledgeCheck:[{q:"Where should a committee discussion about a shared working document usually happen?",a:["In the committee Team","In several personal email threads","Only by telephone"],correct:0}],troubleshooting:["I cannot see my committee Team: confirm that you are signed in with your KPC account, then ask KPC to check your access."],relatedKitchenTalkId:"talk2",status:"written-guide",contentStatus:["Microsoft video available","written guide available","KPC demonstration coming soon"]},
"open-committee-team":{title:"Open your committee Team",description:"Find the Microsoft Team used by your KPC committee.",outcome:"I can open my committee Team and recognize its main areas.",whyItMatters:"This is the starting point for your committee's conversations, meetings and shared files.",estimatedMinutes:3,steps:["Open Microsoft Teams with your KPC account.","Select Teams from the left side.","Find your committee name.","Open the General channel first.","Look for Posts and Files."],practiceTask:"Open your committee Team and locate its Files area.",knowledgeCheck:[{q:"What should you check first if your committee Team is missing?",a:["That you are using your KPC account","That your printer is on","That the file is attached to an email"],correct:0}],troubleshooting:["I opened the wrong Microsoft account: sign out and choose your KPC account.","I still cannot see the Team: ask KPC to confirm your committee access."],relatedKitchenTalkId:"talk2",status:"kpc-demo-needed",contentStatus:["written guide available","KPC demonstration coming soon","screenshots needed"]},
"channels-conversations":{title:"Understand conversations and channels",description:"Keep a reply with the correct committee topic.",outcome:"I can find a channel and reply to the correct conversation.",whyItMatters:"Keeping related replies together makes decisions easier to follow later.",estimatedMinutes:4,steps:["Open the correct committee Team.","Choose the channel that matches the work.","Read the original post and existing replies.","Use Reply under that post instead of starting a separate conversation."],practiceTask:"Find one existing conversation and identify where you would reply.",knowledgeCheck:[{q:"How do you keep your response with the original topic?",a:["Use Reply under the post","Start a new unrelated post","Send a separate attachment"],correct:0}],troubleshooting:["I posted in the wrong place: copy the useful information into the correct conversation and tell the group."],relatedKitchenTalkId:"talk2",status:"written-guide",contentStatus:["written guide available","KPC demonstration coming soon"]},
"find-committee-files":{title:"Find committee files",description:"Locate documents shared by your committee.",outcome:"I can find the committee Files area and open a document.",whyItMatters:"The shared location helps everyone use the same current version.",estimatedMinutes:3,steps:["Open the committee Team.","Choose the correct channel.","Select Files.","Open the folder that matches the work.","Select the document."],practiceTask:"Find and open one committee document without downloading it.",knowledgeCheck:[{q:"Where should you look for a committee's shared working documents?",a:["The Team's Files area","Only your Downloads folder","A personal USB drive"],correct:0}],troubleshooting:["I cannot find the file: check the channel, use search, then ask where the current version is stored.","I do not have permission: ask KPC to check your access rather than requesting someone else's password."],relatedKitchenTalkId:"talk2",status:"kpc-demo-needed",contentStatus:["written guide available","KPC demonstration coming soon","screenshots needed"]},
"edit-shared-document":{title:"Open and edit a shared document",description:"Work in the shared file instead of creating another copy.",outcome:"I can edit the committee's shared document and know my changes are saved.",whyItMatters:"One shared document prevents conflicting versions.",estimatedMinutes:5,steps:["Open the document from the Team's Files area.","Choose Edit in browser when available.","Make a small change.","Look for the saved status before closing.","Return to the Files area and reopen the document if you need to confirm."],practiceTask:"Open a practice document, add a short note and confirm it saves.",knowledgeCheck:[{q:"What is usually better when several people are editing?",a:["One shared file","A new attachment from every person","A printed copy only"],correct:0}],troubleshooting:["I can view but not edit: check whether you opened a read-only copy or ask KPC to review your permission."],relatedKitchenTalkId:"talk2",status:"kpc-demo-needed",contentStatus:["written guide available","KPC demonstration coming soon","practice activity available"]},
"avoid-duplicates":{title:"Avoid duplicate file copies",description:"Recognize when downloading or attaching a file would create another version.",outcome:"I can keep committee work in one current shared file.",whyItMatters:"Duplicate copies make it difficult to know which version contains the latest decision.",estimatedMinutes:3,steps:["Open the shared file from Teams.","Edit it there when possible.","Do not rename and reattach a new copy unless the committee has a specific reason.","Use version history or ask before creating a replacement."],practiceTask:"Look at a recent email attachment and decide whether a shared link would have been clearer.",knowledgeCheck:[{q:"What is the main risk of emailing several edited copies?",a:["No one knows which is current","The text becomes larger","Teams stops working"],correct:0}],troubleshooting:["Several copies already exist: ask the committee to identify one current shared version and move future work there."],relatedKitchenTalkId:"talk2",status:"complete-outline",contentStatus:["written guide available","practice activity available"]},
"send-a-link":{title:"Send a link instead of an attachment",description:"Point people to the current shared file.",outcome:"I can copy and send a link to a committee file.",whyItMatters:"A link keeps everyone working from the same current version.",estimatedMinutes:4,steps:["Find the file in Teams.","Open its More options menu.","Choose Copy link or Share.","Confirm the link is for the intended KPC people.","Paste the link into Teams or KPC email."],practiceTask:"Copy a link to a practice file and paste it into a draft message without sending it.",knowledgeCheck:[{q:"Why is a shared link often better than an attachment?",a:["It opens the current shared version","It removes all permissions","It works without a KPC account"],correct:0}],troubleshooting:["The recipient cannot open the link: confirm they are signed in with the correct KPC account and have access."],relatedKitchenTalkId:"talk2",status:"kpc-demo-needed",contentStatus:["written guide available","KPC demonstration coming soon","screenshots needed"]},
"committee-knowledge-check":{title:"Committee-work knowledge check",description:"Practise realistic choices about conversations and shared files.",outcome:"I can choose the right place for common committee work.",whyItMatters:"A short scenario helps confirm that the workflow makes sense before you need it.",estimatedMinutes:4,steps:["Read each situation.","Choose the action that keeps the work easiest to find.","Review any suggested lesson."],practiceTask:"Complete the Working in KPC game from the Games area.",knowledgeCheck:[{q:"Three volunteers need to update the same spreadsheet. What is the best play?",a:["Use one shared file in Teams","Email three copies","Keep it on one volunteer's computer"],correct:0},{q:"You need to tell the committee where the minutes are. What should you send?",a:["A link to the current shared file","A photograph of the screen","A newly renamed attachment"],correct:0}],troubleshooting:["A question feels unclear: return to the linked lesson and use the KPC example."],relatedKitchenTalkId:"talk2",status:"available",contentStatus:["knowledge check available"]}
};

const lessonPlans={
"start-here":[["m365-overview","What Microsoft 365 is"],["kpc-use-m365","How KPC will use Microsoft 365"],["sign-in-kpc","Sign in to your KPC account"],["find-apps","Find your Microsoft 365 apps"],["set-up-mfa","Set up multifactor authentication"],["unexpected-sign-in","Respond to an unexpected sign-in request"],["get-help","Know where to get help"]],
"email-meetings":[["open-outlook","Open Outlook"],["send-reply-email","Send and reply to email"],["personal-email","Understand your personal KPC email address"],["role-addresses","Understand permanent role addresses"],["shared-mailboxes","Understand shared and functional mailboxes"],["outlook-calendar","Use the Outlook calendar"],["accept-invitation","Accept a meeting invitation"],["join-teams-meeting","Join a Teams meeting"],["share-screen","Share your screen"]],
"files-what-goes-where":[["onedrive-personal-files","OneDrive for personal KPC working files"],["teams-shared-work","Teams for shared committee work"],["sharepoint-lasting-info","SharePoint for organized and lasting KPC information"],["move-draft","Move a personal draft into a shared location"],["find-current-version","Find the current version"],["share-file-safely","Share a file safely"],["official-records","Know where official KPC records belong"],["links-vs-attachments","Understand links compared with attachments"]],
"staying-safe":[["individual-accounts","Why everyone has an individual account"],["no-shared-passwords","Why passwords must not be shared"],["what-mfa-does","What multifactor authentication does"],["suspicious-sign-ins","Recognize suspicious sign-in requests"],["basic-phishing","Recognize basic phishing attempts"],["safe-sharing","Share files safely"],["protect-information","Protect member and volunteer information"],["report-problem","Report a problem"]],
"kpc-administration":[["add-user","Add a user"],["offboard-user","Remove or offboard a user"],["manage-licence","Assign or remove a licence"],["reset-password","Reset a password"],["committee-access","Manage committee access"],["mailbox-permissions","Manage shared mailbox permissions"],["add-administrator","Add another administrator"],["review-access-changes","Review account and access changes"],["admin-continuity","Avoid relying on a single administrator"]]
};

const lessons=[];
Object.entries(lessonPlans).forEach(([pathId,items])=>items.forEach(([id,title])=>lessons.push({id,pathId,title,description:"A short practical KPC lesson.",outcome:`I can ${title.charAt(0).toLowerCase()+title.slice(1)}.`,whyItMatters:"This task supports everyday KPC work and helps information remain easy to find and protect.",estimatedMinutes:4,microsoftVideo:officialVideos[id]||null,kpcVideo:{url:"",status:"coming-soon"},screenshots:[],steps:[],practiceTask:"",knowledgeCheck:[],troubleshooting:[helpContact.instructions],relatedKitchenTalkId:null,status:"outline",contentStatus:[officialVideos[id]?"Microsoft video available":"content under review","KPC demonstration coming soon"]})));
Object.entries(detailedCommitteeLessons).forEach(([id,data])=>lessons.push({id,pathId:"committee-work",microsoftVideo:officialVideos[id]||null,kpcVideo:{url:"",status:"coming-soon"},screenshots:[],lastReviewed:"2026-07-26",...data}));

window.KPCLearning={learningPaths,lessons,officialVideos,helpContact};